// Renders Formula/mclaude.rb for one release: the four release tarballs by
// platform, each with the sha256 the release workflow wrote to SHASUMS256.txt.
// The formula lives in the jnsdls/homebrew-tap repo, so `brew install
// jnsdls/tap/mclaude` works; scripts/publish-brew.sh puts it there.
//
//   bun run scripts/homebrew.ts <version> <path to SHASUMS256.txt>
import { readFileSync } from "node:fs";
import { TARGETS, type Target } from "./platforms.ts";

export const TAP = "jnsdls/homebrew-tap";
export const FORMULA_PATH = "Formula/mclaude.rb";

const REPO = "https://github.com/jnsdls/multi-claude";

/** SHASUMS256.txt, as `shasum -a 256` writes it, keyed by file name. */
export function parseShasums(text: string): Map<string, string> {
  const sums = new Map<string, string>();
  for (const line of text.split("\n")) {
    const m = /^([0-9a-f]{64})\s+\*?(\S+)$/.exec(line.trim());
    if (m) sums.set(m[2]!, m[1]!);
  }
  return sums;
}

function tarball(t: Target): string {
  return `mclaude-${t}.tar.gz`;
}

function sha(sums: Map<string, string>, t: Target): string {
  const s = sums.get(tarball(t));
  if (!s) throw new Error(`SHASUMS256.txt has no line for ${tarball(t)}`);
  return s;
}

/** The whole formula. Throws when a target's tarball is missing from the sums. */
export function formula(version: string, sums: Map<string, string>): string {
  if (!/^\d+\.\d+\.\d+$/.test(version)) throw new Error(`not a release version: ${version}`);
  for (const t of TARGETS) sha(sums, t);
  const block = (t: Target) =>
    [`      url "${REPO}/releases/download/v${version}/${tarball(t)}"`, `      sha256 "${sha(sums, t)}"`].join("\n");
  return `# Generated by scripts/homebrew.ts in jnsdls/multi-claude for each release.
# Edits here are overwritten by the next one.
class Mclaude < Formula
  desc "Run Claude Code under the subscription account with headroom"
  homepage "${REPO}"
  license "MIT"

  on_macos do
    on_arm do
${block("darwin-arm64")}
    end
    on_intel do
${block("darwin-x64")}
    end
  end

  on_linux do
    on_arm do
${block("linux-arm64")}
    end
    on_intel do
${block("linux-x64")}
    end
  end

  def install
    bin.install "mclaude"
  end

  def caveats
    <<~EOS
      mclaude needs Claude Code installed. It finds claude through
      MCLAUDE_CLAUDE_PATH, then claudePath in ~/.mclaude/config.json, then PATH,
      then ~/.local/bin/claude.
    EOS
  end

  test do
    assert_match "mclaude #{version}", shell_output("#{bin}/mclaude version")
  end
end
`;
}

if (import.meta.main) {
  const [version, sumsPath] = process.argv.slice(2);
  if (!version || !sumsPath) {
    console.error("usage: bun run scripts/homebrew.ts <version> <SHASUMS256.txt>");
    process.exit(64);
  }
  process.stdout.write(formula(version.replace(/^v/, ""), parseShasums(readFileSync(sumsPath, "utf8"))));
}
